FORTNITE_LOCATIONS = [
    'Junk Junction',
    'Haunted Hills',
    'Snobby Shores',
    'Pleasant Park',
    'Greasy Grove',
    'Tilted Towers',
    'Shifty Shafts',
    'Flush Factory',
    'Lazy Links',
    'Tomato Town',
    'Dusty Divot',
    'Salty Springs',
    'Fatal Fields',
    'Lucky Landing',
    'Risky Reels',
    'Wailing Woods',
    'Lonely Lodge',
    'Retail Row',
    'Paradise Palms'
]
